### ISSUE TITLE
About prompt to prompt implementation.

### ISSUE THREAD

**Issue by Adenialzz** [kongzhecn/OMG#12]
Hi, thanks for sharing. 

I have one question. What did `width` and `height` [here](https://github.com/kongzhecn/OMG/blob/master/src/prompt_attention/p2p_attention.py#L141) do? It seems different from the original implementation of prompt-to-prompt.

**Comment by kongzhecn** [comment]
In gradio demos, like [this](https://github.com/kongzhecn/OMG/blob/master/gradio_demo/app_generateOne.py#L300), OMG supports generating images with different resolutions. Hence, the size of the attention map should vary with the resolution of the generated images.

**Comment by Adenialzz** [comment]
got it. thanks
