### ISSUE TITLE
Stage 2 Image Generation Adds Excessive Noise in InstantID Pipeline

### ISSUE THREAD

**Issue by bscw21027** [kongzhecn/OMG#14]
In the InstantID pipeline, the images generated in Stage 2 have significant noise and artifacts, which obscures the characters and degrades the image quality. This issue does not occur in Stage 1, where the images are generated correctly.

**Steps to Reproduce**

1. Use the following command to run the pipeline:
```
python inference_instantid.py \
--prompt 'A vibrant comic-style image of a woman sitting by the window, looking at the starry night sky. She smiles, seeing a shooting star streak across the sky.' \
--negative_prompt 'noisy, blurry, soft, deformed, ugly' \
--prompt_rewrite '[a woman sitting by the window, looking at the starry night sky.]-*-[noisy, blurry, soft, deformed, ugly]-*-./example/Johansson.jpg'
```

Stage 1 Result:

![image](https://github.com/kongzhecn/OMG/assets/91588024/d94f645c-3858-4554-a7dd-5c0278404aac)

Stage 2 Result:

![image](https://github.com/kongzhecn/OMG/assets/91588024/5c386972-4c69-4851-b9a4-9bb4314701c4)

2. Compare the images generated in Stage 1 and Stage 2.

**Expected Behavior:**
The image generated in Stage 2 should be a refined version of the Stage 1 image, with applied masks and additional controls, without excessive noise.

**Actual Behavior:**
The image generated in Stage 2 has excessive noise and artifacts that obscure the characters, making the image quality worse compared to Stage 1.

**Comment by kongzhecn** [comment]
The InstantID pipeline supports customization for two people. However, when only one person is generated in the first stage, the  [mask1](https://github.com/kongzhecn/OMG/blob/master/inference_instantid.py#L343) and [mask2](https://github.com/kongzhecn/OMG/blob/master/inference_instantid.py#L348) segments are the same region. As a result, the concept noise blending operation is executed twice on the same mask region in the second stage, leading to abnormal generation results.

**Comment by teenaxta** [comment]
@kongzhecn  Is there a way to fix the issue?

**Comment by kongzhecn** [comment]
> @kongzhecn Is there a way to fix the issue?

You can try to change the code and make `mask1= None` in [mask1](https://github.com/kongzhecn/OMG/blob/master/inference_instantid.py#L342) like this:

original:
```
   if pipe.tokenizer("man")["input_ids"][1] in pipe.tokenizer(args.prompt)["input_ids"][1:-1]:
        mask1 = predict_mask(detect_model, sam, image[0], 'man', args.segment_type, confidence=0.1, threshold=0.5)
    else:
        mask1 = None
```

modify:
```
   
  mask1 = None
```

**Comment by Liming1013** [comment]
> > @kongzhecn Is there a way to fix the issue?
> 
> You can try to change the code and make `mask1= None` in [mask1](https://github.com/kongzhecn/OMG/blob/master/inference_instantid.py#L342) like this:
> 
> original:
> 
> ```
>    if pipe.tokenizer("man")["input_ids"][1] in pipe.tokenizer(args.prompt)["input_ids"][1:-1]:
>         mask1 = predict_mask(detect_model, sam, image[0], 'man', args.segment_type, confidence=0.1, threshold=0.5)
>     else:
>         mask1 = None
> ```
> 
> modify:
> 
> ```
>    
>   mask1 = None
> ```

 "I tried your method, but the original issue still occurs. Could it be that OMG needs to completely replace the character's noise in the last 35 steps, causing an imbalance with the original image?"
