### ISSUE TITLE
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by barraland** [kongzhecn/OMG#5]
ImportError: libcupti.so.11.7: cannot open shared object file: No such file or directory when running test_inference.sh. I have CUDA 11.3 installed. The file was not present in  /usr/local/cuda/lib64 after a clean CUDA 11.3 install, so I created a symbolic link to  libcupti.so.2021.1.1, but it did not help sadly.

Does anyone had same issue and solved it? Thanks a lot

**Comment by kongzhecn** [comment]
Could you please provide additional error information so that I can easily pinpoint the location of the error? Additionally, it seems that there is no 'test_inference.sh' file in the OMG code. Could you share the code from the 'test_inference.sh' file?

**Comment by barraland** [comment]
> Could you please provide additional error information so that I can easily pinpoint the location of the error? Additionally, it seems that there is no 'test_inference.sh' file in the OMG code. Could you share the code from the 'test_inference.sh' file?

Sorry, you are right. This is the simple shell test script I created. 

`#!/bin/bash`
`export CUDA_HOME=/usr/local/cuda-11.3/`
`export LIBRARY_PATH=${CUDA_HOME}/lib64`
`export C_INCLUDE_PATH=${CUDA_HOME}/include`
`python inference_lora.py --prompt "Close-up photo of the happy smiles on the faces of the cool man and beautiful woman as they leave the island with the treasure, sail back to the vacation beach, and begin their love story, 35mm photograph, film, professional, 4k, highly detailed." \
    --negative_prompt 'noisy, blurry, soft, deformed, ugly' \
    --prompt_rewrite '[Close-up photo of the Chris Evans in surprised expressions as he wear Hogwarts uniform, 35mm photograph, film, professional, 4k, highly detailed.]-*-[noisy, blurry, soft, deformed, ugly]|[Close-up photo of the TaylorSwift in surprised expressions as she wear Hogwarts uniform, 35mm photograph, film, professional, 4k, highly detailed.]-*-[noisy, blurry, soft, deformed, ugly]' \
    --lora_path '/mnt/e/lora/chris-evans.safetensors|/mnt/e/lora/TaylorSwiftSDXL.safetensors'`

EDIT: I solved it by forcing a reinstall of CUDA 11.7

`sudo apt-get --purge remove "cuda*`
`sudo apt-get install cuda-toolkit-11-7`
