### ISSUE TITLE
Fixed keywords ?

### ISSUE THREAD

**Issue by Adenialzz** [kongzhecn/OMG#7]
hi, thanks for you release this great work. I have a question here.

https://github.com/kongzhecn/OMG/blob/master/inference_lora.py#L276-L283

is this fixed keywords `man` and `woman` ? what does this mean ? 

Looking forward to your reply.

**Comment by Adenialzz** [comment]
maybe this two keywords just used to make difference masks from stage 1 results? and stage 2 put lora on the different masks to generate different identities?  is my understanding correct?

**Comment by kongzhecn** [comment]
Yes. The overall architecture of the proposed method contains two stages during sampling.  The first stage generates an image containing a man and a woman based on the input text prompt, without considering personalization. After the image segment, the ID of the man and woman can be injected through the mask.

**Comment by Adenialzz** [comment]
OK, I see. Great work.
