### ISSUE TITLE
Question About Lora

### ISSUE THREAD

**Issue by Adenialzz** [kongzhecn/OMG#9]
![image](https://github.com/kongzhecn/OMG/assets/61398820/dd3d05a6-3b92-497f-8893-06336b5e7b2b)
 
 I trained dreambooth lora using diffusers official examples. One lora works fine. But when I using two loras with OMG, some features (the girl's t-shirt color for example) missed. Can you give me some advice to figure out the possible promble? What should I check ?   thanks a lot.

**Comment by kiymetakdemir** [comment]
How do you use dreambooth lora, do you give rare token in prompt_rewrite? Could you provide an example?

**Comment by Adenialzz** [comment]
I add the rare token in region prompts. Other settings are same with the LoRA example in this repo.
